# command code
# author:noble
# time:2018-5-11
# vision:0.0
#

- hosts: nfs
  tasks:
    - name: step01:install nfs
      yum: name=nfs-utils state=installed
    - name: step02:install rpcbind
      yum: name=rpcbind state=installed
    - name: step03:edit configrate file
      shell: echo '/data 172.16.1.0/24(rw,sync)' > /etc/exports
    - name: step04:create share directory
      file: name=/data state=directory owner=nfsnobody group=nfsnobody
    - name: step05:run rpcbind
      shell: /etc/init.d/rpcbind start
    - name: step06:run nfs
      shell: /etc/init.d/nfs start

- hosts: web
  tasks:
    - name: step01:install nfs 
      yum: name=nfs-utils state=installed
    - name: step02:install rpcbind
      yum: name=rpcbind state=installed
#    - name: step03:mount the directory
#      shell: mount -t nfs 172.16.1.31:/data /mnt
